---
- name: Configure Minecraft Server
  hosts: all
  become: true

  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
      become: yes

    - name: Create minecraft directory
      file:
        path: /home/ubuntu/minecraft
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download Minecraft server jar
      get_url:
        url: "https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar"
        dest: /home/ubuntu/minecraft/server.jar
        mode: '0755'

    - name: Accept EULA
      copy:
        dest: /home/ubuntu/minecraft/eula.txt
        content: "eula=true\n"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Set ownership of Minecraft files
      file:
        path: /home/ubuntu/minecraft
        state: directory
        recurse: true
        owner: ubuntu
        group: ubuntu
    - name: Create Minecraft systemd service file
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Minecraft service
      systemd:
        name: minecraft
        enabled: yes

    - name: Start Minecraft service
      systemd:
        name: minecraft
        state: started
